version: '3.1'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/gary_data:/var/lib/postgresql/data
  app:
    environment:
      MAPTILER_API_KEY: ${MAPTILER_API_KEY}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      FEATURE_PASSWORD_RESET: ${FEATURE_PASSWORD_RESET}
      SEED: ${SEED}
    build:
      context: .
      dockerfile: Dockerfile
    image: backendv2:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ${HOME}/gary_logs:${HOME}/gary_logs
