version: '3.1'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backendv2:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
